### ISSUE TITLE
remove any functionality allowing private members to be set

### ISSUE THREAD

**Issue by garethdown44** [nbuilder/nbuilder#11]
don't want nbuilder to be able to do this.

**Comment by austinoriginal** [comment]
I second this one.  Can change the behavior with implementing your own property namer but that seems a long way around.  I don't think it should be setting privates.

**Comment by douglasg14b** [comment]
RIP. Artificial constraints on tooling just creates pain. Especially when it's something meant for test mocking where you often want more interesting behavior.

**Comment by garethdown44** [comment]
> "Who's digging wet concrete?" said the makers, not realizing this isn't all that uncommon.

To follow your analogy "The makers" in this case:

- designed and produced the shovel, originally for their own needs
- then gave the shovel away for free, for the benefit of others, at the expense of their own time, for no financial reward
- gave the design away to the world for free so that they could use them as a basis to make their own shovels

If you want a non-flacid shovel so much, and people are crying out for it so much, the makers suggest you should feel empowered to take the free shovel designs, and adjust them according to your own needs to remove the flaccidity when it encounters wetness.

Or feel free to design your own shovel from scratch that stays fully erect at all times.

**Comment by DHemken97** [comment]
I agree with [douglasg14b](https://github.com/douglasg14b)
There may be times you want to test behaviors that requires private variables to be set. test tools should be as flexible as possible to accommodate the users. Good design dictates you should remove anything that is not absolutely necessary to achieve the goal, in this case building an object for unit testing. If the person writing the tests wants to set private variables that should remain their prerogative.  
Side Note: This may be considered a breaking change. leading to less overall stability and ease of use.

**Comment by PureKrome** [comment]
> There may be times you want to test behaviors that requires private variables 

nope.

**Comment by douglasg14b** [comment]
> nope. (as in .. testing PRIVATE variables directly)

Testing public member that are constrained by private fields. Such as entities with private field access in ORMs like EF Core that expose public IENumerables which are used as navigational properties.

This is the same concept, just because _you_ can't think of the reason why, doesn't mean there isn't one.

**Comment by PureKrome** [comment]
example code please? I don't understand what you just said :(
