### ISSUE TITLE
RandomGenerator: Decimal separator wrong for some cultures

### ISSUE THREAD

**Issue by szyb** [nbuilder/nbuilder#19]
Hi,

I use culture pl-PL and there is an error when trying to generate decimal value:
"Input string was not in a correct format." The reason is that decimal separator for my culture is comma(,) and not dot (.).

BR,
Szymon

**Comment by PureKrome** [comment]
My suggestion here is to close this issues as 'not-our-fault' and get Poland (and many other countries in the EU, South America, etc) to fix up their language and use dots (.) not comma's (,) for their decimal separator. It is called a _decimal_ separator, after all.


...

..

.

Joke!! just joking!!! :sunglasses:

**Comment by crmckenzie** [comment]
I'm going to need repro steps on this one. I'm not sure which function is supposed to be a problem. I tried setting the `CurrentCulture` to Poland in some existing tests involving decimals to smoke it out, but everything looks good.

**Comment by crmckenzie** [comment]
I explained the problem to a rubber duck and found the issue.

**Comment by PureKrome** [comment]
:clap:
