### ISSUE TITLE
NuGet package out of date

### ISSUE THREAD

**Issue by skipperTux** [nbuilder/nbuilder#22]
Hi. NBuilder NuGet package is last published on 2011-11-14, but there has been recent activity (June 2014) even in the Nuspec file, NBuilder package creation, Teamcity Generation of NuGet package. Why is the NuGet update broken?
Thanks for the great tool.

**Comment by ogborstad** [comment]
bump, will you update the package any time soon?

**Comment by ghuntley** [comment]
No Nuget.org push in 4 years?

![](http://www.reactiongifs.com/r/yuck.gif)

**Comment by pjmagee** [comment]
get rekt mate

**Comment by AbubakerB** [comment]
that gif. 360 REKT MATE

**Comment by ghuntley** [comment]
![](http://media.giphy.com/media/kdpDNdzCO3HnW/giphy.gif)

**Comment by phatcher** [comment]
Another bump

**Comment by kibiz0r** [comment]
Bump. I want the index parameter support.

**Comment by sslotsky** [comment]
Major bump.

**Comment by crmckenzie** [comment]
I've recently begun co-managing the project. I am working on getting an automated build in place that we can rely on. As soon as that's done, a new nuget package will be forthcoming.

**Comment by phatcher** [comment]
Chris, if you want a hand, let me know

**Comment by crmckenzie** [comment]
This will be resolved soon. What's left:
1) SL5 & License discussion points
2) attempt to fix technical issue with Guid incrementor.

I'm closing the issue because releasing the package will resolve it and I want the Milestone cleared.

CC: @garethdown44

**Comment by pjmagee** [comment]
Just to note its not just guids. ^^
