### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sjswoboda** [nbuilder/nbuilder#26]
Couldn't find a license file in the source. 

Is it MIT? MIT would be great! We usually have organizational trouble with LGPL but MIT works very well.

Thanks

**Comment by ghuntley** [comment]
![](http://www.reactiongifs.com/r/jfp.gif)

**Comment by pjmagee** [comment]
lol rekt

**Comment by RyannosaurusRex** [comment]
+1 Would be cool to officially put a license up on the readme.md.  If the proj owner(s) could let us know which one (my vote would be MIT, but it's up to them), I'm sure someone would be happy to do a PR.

**Comment by pjmagee** [comment]
The original source repo on Google code had the GNU license. https://code.google.com/p/nbuilder/

**Comment by pjmagee** [comment]
@garethdown44  Should we add a LICENSE file to the repository. We can update the READ ME with a link to the LICENSE file with a URL. 

Also, what License?

**Comment by PureKrome** [comment]
Need to add a license to the repo and readme IMO.

**Comment by PureKrome** [comment]
I also vote for the lic to be changed to MIT plz.

GNU vs MIT : http://stackoverflow.com/a/11752204/30674

**Comment by garethdown44** [comment]
Is there a compelling reason to switch to MIT? I like the fact that GPL means any modifications have to remain open source.

**Comment by PureKrome** [comment]
This is just my 2c:

Will people _really_ give a care and think "i better release my code modifications or else i'll get in trouble" ? I think they will generally just change some code (if they even mod the code base) and just move on with their life. Yes, we'd love modifications to be PR'd up or OSS'd but ... meh.

In essence, GPL is nice and hippy. In effect, I don't think it will really sway people or they might care.

MIT is more realistic, IMO. So maybe just stick with what's more realistic.

/shrug.

**Comment by garethdown44** [comment]
This is the scenario I want to be able to stop:

"CompanyX takes NBuilder, changes the code around a little bit, makes a few small improvements and incorporates it into their commercial testing product. They advertise a feature of test object generation, without any mention of where it came from. They don't give any credit to where they got the code from and don't give back any changes they make to the community"

I don't claim to know much about licenses but I'm pretty sure GPL would stop that.

What I don't care about is: "Someone uses it to test their own product, even modifies it a little bit to suit their needs and doesn't give us the changes they made"

If we would be able to legally go after any company that has done the first scenario, even with the MIT licence, then I don't mind if it gets changed.

**Comment by sjswoboda** [comment]
As part of MIT,

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

They cannot remove the existing copyright notices.

**Comment by crmckenzie** [comment]
It sounds like MIT satisfies @garethdown44 's concerns. I'm going to plan on adding the MIT license.
