### ISSUE TITLE
parallelism and NBuilder

### ISSUE THREAD

**Issue by jasoncavaliere** [nbuilder/nbuilder#36]
Hi guys, 

Not sure if anyone is actively contributing to this any more, looks like very minimal lately.

We had an issue when converting our Nunit tests to XUnit for parallel capabilities, and had make some mods to the source in order to get everything working, making the Builder<T> and the BuilderSetup instance based rather than static.  

Would you be interested in a pull request, or should we fork?  We'd love for this to be rolled in and not have to maintain our own copy, but there was no way to work around the issue.  If you're interested in looking at the changes we made let's chat!

-Jason

**Comment by CL0SeY** [comment]
We've been experiencing similar problems. Would be great to have the fork available on GH to reference at least. Then it can be turned into a pull request potentially?

**Comment by pjmagee** [comment]
AutoFixture seems to be the way to go now.

**Comment by jasoncavaliere** [comment]
I added the pull request.   

https://github.com/garethdown44/nbuilder/pull/37

Works for us, the only difference is having to pass around a BuilderSetup() which we new up at the beginning of our tests

**Comment by crmckenzie** [comment]
NBuilder is being maintained. I'm working on a catch-up release now. I'm still getting my sea-legs under me as co-manager of the project, so it will likely take a little while.

**Comment by PureKrome** [comment]
Polite bump - any news on this?

**Comment by crmckenzie** [comment]
It looks like the pull request has been integrated. There are still a couple of bug fixes I want to finish before the next release, as well as reaching a final decision on what to do with the Silverlight build. You can track what's happening (or submit PR's) with the "Catch-up Release" milestone.
