### ISSUE TITLE
Setup labels for issues

### ISSUE THREAD

**Issue by pjmagee** [nbuilder/nbuilder#41]
@crmckenzie We have 23 issues and being able to filter issues on labels will help us begin to prioritise and organise Nbuilder.

I propose the following Labels:

Bug: Bug in NBuilder logic 
Core: NBuilder core logic improvement / refactoring 
Feature: A new feature requested from an issue
Needs more info: Someone has submitted an issue but we need more information to investigate 
api needs work: The core of NBuilder may support a proposed feature, but the NBuilder API needs some work in order to facilitate it.
Dev ops: CI / NuGet / Builds

**Comment by PureKrome** [comment]
and `discussion` or `question` - the issue is a convo ... that is been chatted about but not yet closed.

**Comment by crmckenzie** [comment]
I agree completely--though I think I would prefer to use gitter.im for conversations. @pjmagee do you want to take on the initial categorization?

**Comment by pjmagee** [comment]
Sure.

**Comment by pjmagee** [comment]
@crmckenzie , I cannot add Labels/Milestones to the project due to permissions.

**Comment by crmckenzie** [comment]
Turns out I can't either. @garethdown44 can you grant rights to create and apply labels to issues?

**Comment by crmckenzie** [comment]
I've got permissions sorted out. I've added labels and milestones for most issues.
