### ISSUE TITLE
WithConstructor seems to resolve constructor parameters and only once

### ISSUE THREAD

**Issue by worldspawn** [nbuilder/nbuilder#42]
Consider this usage:

```
.CreateListOfSize(5)
.All()
.WithConstructor(() => new Registration(Faker.Internet.Email(), RegistrationType.Beneficiary))
```

Passes the same email to the constructor for every time it creates the object. It should not do that.

Your code

```
var constructorArguments =
                (from argument in ((NewExpression)constructor.Body).Arguments
                select Expression.Lambda(argument).Compile().DynamicInvoke()).ToArray();
```

Resolves once and uses the same args over and over. Seems quite inappropriate for what this library does and the efforts you've made elsewhere to introduce randomness. You discard the constructor expression but why not use it to instantiate the object?

Consider this class

```
public class User 
{
  public Foo(string emailAddress)
  {
    EmailAddress = emailAddress;
  }

  public string EmailAddress { get; protected set; }
}
```

So anywhere we have a class with a constructor that initialises a member that is protected it becomes unusable with the CreateListOfSize method. I'd need to loop myself and provide a different expression each time.

**Comment by crmckenzie** [comment]
This is an interesting idea, but I imagine the reason the WithConstructor logic was put into place was to handle situations in which the constructor depended on some external service:

```csharp
.CreateListOfSize(5)
.All()
.WithConstructor(() =>  new Registration(new RegistrarService()) )
;
```

NBuilder wouldn't be able to introduce randomness into these kinds of constructors.
Thoughts?

**Comment by worldspawn** [comment]
I'm not sure that makes any difference. If it was the intention of the user to share the registrar service between instances then they can instantiate it outside of the expression and use a and refer to the instance in the expression.

Randomness, at least in my example is introduced by me rather than nbuilder. Perhaps I am not understanding your point

**Comment by crmckenzie** [comment]
I think it was me who wasn't understanding your point. You're just saying you want the constructor expression to be recompiled and executed for each item in the list. That makes sense to me, though my gut says it should be optional.

**Comment by worldspawn** [comment]
I don't think it even needs to be recompiled. Compiled once to Func<T> and called for each, it should do what I want it to.

Other perhaps being a breaking change in behavior I don't see why it should be optional. The caller will have the control over whether a value is reused of not. 

New service per instance
```
WithConstructor(() =>  new Registration(new RegistrarService()) )
```
Shared instance
```
var svc = new RegistrarService();
//...
WithConstructor(() =>  new Registration(svc) )
```

But it's your library :)

**Comment by crmckenzie** [comment]
The breaking change is what I'm worried about. I see your point about just re-using the func. This is a good idea. Thanks!

**Comment by cullimorer** [comment]
So was this ever implemented? I want the same, to construct an object with different values on each new instantiation. Is that possible?

**Comment by crmckenzie** [comment]
As implemented I can't really address this issue without making a breaking change to the Fluent API. Specifically, NBuilder is expecting a constructor expression as an argument to `WithConstructor()`. There are 2 issues with this:
1. The expression is not actually a `Func<T>` which is what I was expecting when I read it.
2. `Func<T>` cannot be easily converted to an Expression<Func<T>>, which you can see by trying the following code:

```csharp
            // does not compile
            var users = new Builder().CreateListOfSize<User>(2)
                .All()
                .WithConstructor(() =>
                    {
                        return new User($"Email{i}@nowhere.com")
                    })
                .Build()
                ;
```

The simpler solution would be to add a new method to the API called `WithFactoryMethod()` that just takes a `Func<T>`. This raises a question about what to do if the caller provides both `WithConstructor()` and `WithFactoryMethod()` in their build instructions. Which one takes precedent? Perhaps the solution is to throw an exception if the caller attempts to use both. I need to resolve this question before I can proceed.

Thoughts?

**Comment by PureKrome** [comment]
Bummer re: issue 2 because having a `Func<T>` argument with `WithConstructor()` would be soo much easier to read/grok vs another extension method.

(just thinking out a loud)

**Comment by crmckenzie** [comment]
yeah--but look how complex this part of the code already is:

```csharp
        public T Construct(int index)
        {
            bool requiresArgs = reflectionUtil.RequiresConstructorArgs(typeof(T));

            if (typeof(T).IsInterface())
                throw new TypeCreationException("Cannot build an interface");

            if (typeof(T).IsAbstract())
                throw new TypeCreationException("Cannot build an abstract class");

            T obj;

            if (_constructorExpression != null)
            {
                obj = _constructorExpression.Compile().Invoke(index);
            }
            else if (requiresArgs && constructorArgs != null)
            {
                obj = reflectionUtil.CreateInstanceOf<T>(constructorArgs);
            }
            else if (constructorArgs != null)
            {
                obj = reflectionUtil.CreateInstanceOf<T>(constructorArgs);
            }
            else
            {
                obj = reflectionUtil.CreateInstanceOf<T>();
            }

            return obj;
        }

```

How many reflective `if` cases do you want to support? I'd much rather mark this method obsolete and point to the new (cleaner) method.

**Comment by PureKrome** [comment]
Can you make this method obsolete and then add a new one, though ALSO called `WithContructor(F<T>)` ?

**Comment by crmckenzie** [comment]
I could--but it would violate the principle of least surprise. Further, there's nothing about `Func<T>` that implies or requires "constructor"--but Factory Method fits the bill exactly.

**Comment by cullimorer** [comment]
Hey guys, apologies I'm not sure if I was confused by the thread topic. I was finding when I used the WithConstructor() and setting the value that it was using that value for all constructed entities, which isn't great for testing purposes. The way I got around it was to use Faker.NET with NBuilder but mock out the entity I wanted with a call to Faker to set the default property each time. 

With the below, it was Person that didn't have a parameterless constructor but I got around it like so:

`public class MockPerson : Person
        {
            private MockPerson() : base(GetRandomName())
            {
            }

            private static PersonName GetRandomName()
            {
                return new PersonName(Faker.Name.First(), Faker.Name.Last(), AutomationNodeName.Unspecified);
            }
        }`

**Comment by fromm1990** [comment]
I also found the behavior, pointed out by the original comment, strange. When would it be convenient to have a list of size _x_ of identical items?

However I came up with a temporary fix for my project:

First create an extension method
```cs
public static class ExtensionMethods
    {
        public static IList<T> CreateListOfSize<T>(this Builder builder, int size, Expression<Func<T>> constructorBuilder)
        {
            return new List<T>();
        }
    }
```

Then initialize the Builder:
```cs
var builder = new Builder();
var list = builder.CreateListOfSize(10, () => new Coordinate2D(Faker.RandomNumber.Next(-90, 91), Faker.RandomNumber.Next(-180, 181)));
```

It should be mentioned that this strategy does not support `.All`, `.With`, `.And` etc. as the one shown in @cullimorer's comment would do, however, it will not require to mock every class that has a parameterized constructor.

**Comment by crmckenzie** [comment]
I came to my senses. From the release notes:

* Breaking Change: `WithConstructor` 
  * No longer takes an `Expression<Func<T>>`. 
  * Takes a `Func<T>`.
  * Marked `[Obsolete]` in favor of `WithFactory`
  * This change was to address an [issue](https://github.com/nbuilder/nbuilder/issues/42) in which the constructor expression was not being reevaluated for each item in a list.
