### ISSUE TITLE
Replace ActiveRecord in Tests w/ EntityFramework

### ISSUE THREAD

**Issue by crmckenzie** [nbuilder/nbuilder#47]
Castle.ActiveRecord is no longer maintained (since 2012). It is out of sync with Iesi.Collections which makes it impossible to upgrade any packages. This is test & demo code only, so I'm going to update the persistence tests to use EntityFramework instead. I will also use an in-memory database so that no external setup is required to run the tests. This should make it easier for potential contributors.

**Comment by PureKrome** [comment]
Good stuff @crmckenzie :)
