### ISSUE TITLE
new Builder<T> should include a default ctor.

### ISSUE THREAD

**Issue by PureKrome** [nbuilder/nbuilder#49]
So I was peeking at some new code pushed up to `dev` branch (sneaky me!) and noticed this.

```
        public Builder(BuilderSetup builderSetup)
        {
            _builderSetup = builderSetup;
        }
```

Sweet. Just like your **breaking changes** doc says -> Builder is no longer static.

But .. everytime i create a builder i have to _manually_ also create a new `builderSetup`????

what about this..

```
public Builder() : this(new BuilderSetup())
{
}

public Builder(BuilderSetup builderSetup)
{
    if (builderSetup == null)
    {
        throw new ArgumentNullException(nameof(builderSetup));
    }

    _builderSetup = builderSetup;
}
```

**Comment by crmckenzie** [comment]
[see here](https://github.com/nbuilder/nbuilder/blob/develop/Source/FizzWare.NBuilder/Builder.cs) :smile:

**Comment by PureKrome** [comment]
i'm not sure if having a single ctor with the optional is still considered a default ctor .. so things like JSON.net will fail when it tries to use a default ctor.

(yes, i know there's no reason to serialize an `Builder` instance, etc.. just thinking out aloud for possible problems...

**Comment by crmckenzie** [comment]
Point taken. Code updated.

**Comment by PureKrome** [comment]
wow! PR's coming, so fast!! :clap: :clap: 

![](http://i.giphy.com/Ctzm5rEEhqjNm.gif)
