### ISSUE TITLE
If Builder is going to be instance-based, it should be Builder instead of Builder<T>

### ISSUE THREAD

**Issue by crmckenzie** [nbuilder/nbuilder#51]
Further, this instance-based change is going to break a lot of code. I'm planning on restoring Builder<T> as static and marking it obsolete to be deleted in the 5.0 release along with .net core support.

**Comment by PureKrome** [comment]
Question: Will it be `Builder<T>` in v 5?

**Comment by crmckenzie** [comment]
I don't think so. Instead, the methods on Builder should be generic. I don't want to have to create a separate builder for every type I want to build. In my mind, a builder maps to a BuilderConfiguration, but I should be able to build multiple types from the same configuration.

```csharp
  var builder = new Builder(new MyBuilderConfiguration());
  var customers = builder.CreateListOfSize<Customer>(5);
  var products = builder.CreateListOfSize<Product>(25);
  // etc
```
