### ISSUE TITLE
NextString output not withing min and max

### ISSUE THREAD

**Issue by KWodarczyk** [nbuilder/nbuilder#57]
This test will fail at some point the values generated are not withing the min and max, just added a loop to the already existing text

`
[Test(Description = "Tests the NextString returns a string that is between the minimum and maximum values specified")]
        public void 
            ShouldBeBetweenMinAndMaxNextString()
        {

            // Arrange
            int minValue = 100;
            int maxValue = 200;
            

            for(int i=0; i<100;i++)
            {
                // Act
                var result = randomGenerator.NextString(minValue, maxValue);

                // Assert
                Assert.That(result.Length, Is.LessThanOrEqualTo(maxValue));
                Assert.That(result.Length, Is.GreaterThanOrEqualTo(minValue));
            }
            
        }
`

**Comment by crmckenzie** [comment]
The easiest fix here is to remove the `Trim()` statement at the end of the method. However, I'll bet that breaks some assumptions others have what constitutes a valid string. The other thing I have to be concerned about is narrow ranges (e.g., `NextString(15,20)`). This will likely require a complete rewrite of the  method. Should be fun.

**Comment by crmckenzie** [comment]
Okay, this is the new test body and it passes:

```csharp

        [Test(Description = "Tests the NextString returns a string that is between the minimum and maximum values specified")]
        [TestCase(1,10)]
        [TestCase(4, 5)]
        [TestCase(16, 20)]
        [TestCase(100, 200)]
        public void ShouldBeBetweenMinAndMaxNextString(int minLength, int maxLength)
        {
            // Arrange
            for (int i = 0; i < 100; i++)
            {
                // Act
                var result = randomGenerator.NextString(minLength, maxLength);

                // Assert
                Assert.That(result.Length, Is.LessThanOrEqualTo(maxLength), result);
                Assert.That(result.Length, Is.GreaterThanOrEqualTo(minLength), result);
            }

        }

```

**Comment by KWodarczyk** [comment]
wow my for loop is now part of he source code ? I feel honored :P

**Comment by crmckenzie** [comment]
The fastest way to get your issue worked on is to provide a nice, easy test case. Thanks for your effort! 👍
