### ISSUE TITLE
Convert Rhino.Mocks to NSubstitute

### ISSUE THREAD

**Issue by crmckenzie** [nbuilder/nbuilder#58]
Rhino.Mocks appears to be unsupported and has not been ported to .NET Core. NSubstitute has. Convert the unit tests to use NSubstitute instead.

**Comment by PureKrome** [comment]
or .. xunit? xunit is the default testing framework for vnext stuff, it seems. 

Source: [ASP.NET repo engineering guidelines](https://github.com/aspnet/Home/wiki/Engineering-guidelines#unit-tests).
