### ISSUE TITLE
Generating short phrase occassionally results in empty string

### ISSUE THREAD

**Issue by CODave4** [nbuilder/nbuilder#60]
When calling RandomGenerator.Phrase with a max length of 10 it will sometimes return an empty phrase when any of the latin words longer than the short max length resulting in an empty string.  Expected is always return a non-empty phrase less than or equal to the max length.

**Comment by crmckenzie** [comment]
Sweet! Bonus points if you can provide a unit test. :)

**Comment by crmckenzie** [comment]
I added this test and was unable to reproduce:

```csharp
        [Fact]
        public void RandomGenerator_WithShortPhrase_NeverReturnsEmptyString()
        {
            // Arrange
            for (var i = 0; i < 10000; i++)
            {
                // Act
                var result = randomGenerator.NextString(1, 10);

                // Assert
                result.Length.ShouldBeInRange(1,10);
            }

        }
```

**Comment by EmanterolaDN** [comment]
It happened to me... Maybe @dgaffield was referring to .Phrase() rather than .Next(x,y)
failed even instantiating the object outside loop and reusing it... @crmckenzie 

![image](https://user-images.githubusercontent.com/73877504/118261535-f8212700-b4b3-11eb-93e6-7ac261f60524.png)

        [TestMethod]
        public void RandomGenerator_WithShortPhrase_NeverReturnsEmptyString()
        {
            // Arrange
            for (var i = 0; i < 10000; i++)
            {
                // Act
                var result = new RandomGenerator().Phrase(new Random().Next(0, 9));

                // Assert
                result.Length.Should().BeGreaterThan(0);
            }
        }

        [TestMethod]
        public void RandomGenerator_WithShortPhrase_NeverReturnsEmptyString2()
        {
            RandomGenerator randomGenerator = new RandomGenerator();
            // Arrange
            for (var i = 0; i < 10000; i++)
            {
                // Act
                var result = randomGenerator.Phrase(new Random().Next(0, 9));

                // Assert
                result.Length.Should().BeGreaterThan(0);
            }
        }

CC/ @juanmalm, @jfjalburquerque

**Comment by EmanterolaDN** [comment]
@dgaffield @crmckenzie I've done a workaround for those testing cases  USING NEXTSTRING:
![image](https://user-images.githubusercontent.com/73877504/118262727-9a8dda00-b4b5-11eb-8f77-6f201c903495.png)


        [TestMethod]
        public void RandomGenerator_WithShortPhrase_NeverReturnsEmptyStringNextString()
        {
            RandomGenerator randomGenerator = new RandomGenerator();
            // Arrange
            for (var i = 0; i < 10000; i++)
            {
                // Act
                int len = new Random().Next(1, 9);
                var result = randomGenerator.NextString(len, len);

                // Assert
                result.Length.Should().BeGreaterThan(0);
            }
        }
