### ISSUE TITLE
Using factory methods rather than constructor

### ISSUE THREAD

**Issue by steverobprice** [nbuilder/nbuilder#63]
We are using some factory methods to create our domain objects rather than using the constructor. It would be great to be able to use the `WithConstructor` extension (or something similar) to create the objects. Below is an example:

```
CreateListOfSize(20)
.All()
.WithConstructor(() => Visit.Create(Guid.NewGuid(), new DateTime(2017, 05, 09, 09, 30, 00), new DateTime(2017, 05, 09, 09, 45, 00)))
```
As the `WithConstructor` extension expects the a new expression, the above code throws an exception at runtime.

Any suggestions?

**Comment by crmckenzie** [comment]
Addressed in 6.0.0 by issue #42
