### ISSUE TITLE
404 for https://github.com/Documentation/Configuration 

### ISSUE THREAD

**Issue by dgroh** [nbuilder/nbuilder#64]
I'm looking for samples of `PersistenceService` , `SetCreatePersistenceMethod` and `SetUpdatePersistenceMethod`but I'm not findind anything. Is there a way of persisting data in NBuilder without using an ORM for Mocking purposes? Any sample somewhere?

**Comment by lorddev** [comment]
@dgroh The url in that link is a typo. Try https://github.com/nbuilder/nbuilder/wiki/Configuration

**Comment by crmckenzie** [comment]
I fixed the link in the wiki.
