### ISSUE TITLE
DLL in NuGet package for v.5.0.0 is not strongly-named

### ISSUE THREAD

**Issue by hilari0n** [nbuilder/nbuilder#70]
It seems that when switching to multi-target project (#55, [commit 624a229](https://github.com/nbuilder/nbuilder/commit/624a229a89fc797538224600bd02116c78020a43)) the reference to the strong-name signing key file was dropped (the SNK file is still there).
This resulted in the new binaries lacking the strong name (including the NuGet package release).

Please consider bringing the strong-name back, and releasing a new NuGet package.

**Comment by kennfarbe** [comment]
I need the strong-name, too.

**Comment by PureKrome** [comment]
Don't forget, you can clone, compile + SN yourself, as an interim step.
