### ISSUE TITLE
Is documentation out of date?

### ISSUE THREAD

**Issue by GuerrillaCoder** [nbuilder/nbuilder#78]
I am new to NBuilder but the docs don't seem to line up with functionality.  For instance `.WhereAll()` doesn't exist but there is a `.All()` method.

**Comment by sorcer1** [comment]
I have the same issue.

**Comment by crmckenzie** [comment]
Yes. The documentation is old and out of date with the actual API. I've been addressing these problems where I find them. If you find other examples of this please file issues--or better yet, submit a PR. :)
