### ISSUE TITLE
NBuilder doesn't work with structs

### ISSUE THREAD

**Issue by IvanZaporozhchenko** [nbuilder/nbuilder#82]
I have following code:

```
public struct TestData
{
    public string Name { get; set; }
}

public class TestClass
{
     [Test]
        public void Test()
        {
            var result = GetTestData();
            Assert.AreEqual(result[0].Name, "Name");
        }

        public List<TestData> GetTestData()
        {
            return Builder<TestData>.CreateListOfSize(1)
                .All()              
                .With(x => x.Name = "Name")
                .Build()
                .ToList();
        }
}
```

This test fails. Name equal null. It is all the same for the structs.
Do you have structs support on the roadmap?

**Comment by crmckenzie** [comment]
Because of how structs are treated in the framework when passed ByVal, they cannot be supported with the current NBuilder design. The library would essentially have to be completely rewritten to support structs which is not feasible.
