### ISSUE TITLE
Ability to call builder.createnew with runtime types?

### ISSUE THREAD

**Issue by fuzzbuzzz** [nbuilder/nbuilder#89]
hi, 

Great lib!

I needed to create test objects with runtime types, so I did this:
[entityType is type of System.Type]
            // Arrange
            var nBuilderType = typeof(Builder<>).MakeGenericType(entityType);
            dynamic generated = nBuilderType.GetMethod("CreateNew").Invoke(null, null);
            var expected = generated.Build();

Can you implement a non-generic version of the builder, so that it is possible to call it with a type? 
Like: Builder(Type testObject).CreateNew().Build()

I haven't checked the code, just wondering if it makes sense on your side?

Thanks!

**Comment by crmckenzie** [comment]
It could make sense. Let me look at it and get back to you.

**Comment by crmckenzie** [comment]
It's do-able but non-trivial. The challenge is that `Builder<T>` uses `ObjectBuilder<T>`, so the generic arguments flow pretty deeply. I'd need to create three overloads for `CreateNew` and `CreateListOfSize`. I'll spend some time with it and see if it falls fast.

**Comment by crmckenzie** [comment]
I'm open to being persuaded, but I don't think this can work. Overloading the above methods is the easy part. The hard part is the fluent API that hangs off of `CreateNew` and `CreateListOfSize`.  It would be an enormous amount of work to rewrite all of that and I'm not even sure what the method signatures would look like.  I'm going to close this for now. If you see a path through the mess then feel free to reopen it.
