### ISSUE TITLE
CreateListOfSize problem when running tests in parallel

### ISSUE THREAD

**Issue by oviradoi** [nbuilder/nbuilder#91]
We are trying to run unit tests in parallel in our codebase using NUnit, and we have noticed that when creating a list using `CreateListOfSize`, the generated objects don't always have the same property values.

Here is an example:

	public class Person
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}

	[TestFixture]
	[Parallelizable(ParallelScope.All)]
	public class TestClass
	{
		private const int LIST_SIZE = 10;

		[Test]
		public void TestMethod([Range(0, 10)] int param)
		{
			IList<Person> persons = Builder<Person>.CreateListOfSize(LIST_SIZE).Build();
			for (int i = 0; i < LIST_SIZE; i++)
			{
				Assert.AreEqual(i + 1, persons[i].Id);
				Assert.AreEqual("Name" + (i + 1), persons[i].Name);
			}
		}
	}

When I run this test in parallel, some of the tests randomly fail. If I run it again, some other methods fail. Sometimes the ids do not match, and other times the names do not match.

If I remove the `Parallelizable` attribute, the tests always run successfully.

Is there any way to get consistent, repeatable property values when running tests in parallel?

**Comment by mcockrellsana** [comment]
We had the same issue, to solve it when using the creation of list's we had to explicitly set the properties we were concerned about in our tests.

**Comment by oviradoi** [comment]
I have also used that workaround, but when you have a lot of properties you end up adding a lot of code into your tests and it leads them to becomming cluttered. It would be a lot better for this to be fixed.

**Comment by mcockrellsana** [comment]
The bigger issue is auto incrementing int properties in these lists.  In parallel tests, for some reason the auto incrementing either skips a number, duplicates a number or entirely fails at setting the property.  So for any field we use in tests, we just set it now, it's still much cleaner than hand writing a large entity out.  We also narrow our tests to usually only 3 to 6 sets in lists.  Usually no need to go larger as it doesnt provide any new logical benefit of business rules.

I'm not sure how to fully resolve the issue, but I dont think his code is thread safe (just guessing).  You could try and modify it.  If you do and have success please let me know.

**Comment by mcockrellsana** [comment]
After more investigation, this same issue also seems to occurs in CreateNew, it's not as prevalent, but I've seen issues with int properties being expected to be created with 1 (since you are creating only one instance) but in reality they are either null, 0, or something else. I think the entire nbuilder package needs a once over to be thread and parallel safe. @oviradoi would you be willing to fix and write tests for CreateNew as well?

**Comment by oviradoi** [comment]
When creating this pull request, I tried reproducing the same issue for `CreateNew`, but I have not been able to. 

Looking at the code, it looks like `CreateNew` uses the `SetValuesOf<T>(T obj)` method from `SequentialPropertyNamer`. That method always sets the `_sequenceNumber` to 1, so the different threads always use the sequence number of 1.

I can't see this issue happening for `CreateNew`. Maybe, just to be safe, we can use the same fix for `CreateNew`, but I'm not sure how to write a unit test for this case.

**Comment by mcockrellsana** [comment]
Wouldn't the test be very similar to your threaded test for the list?  Just replacing the list and foreach shouldbe's with a CreateNew call with SimpleClass, and then verifying all properties are 1?

I've implemented your test and fix for the parallel list issue locally and it sure indeed does fail without the fix you've put in place for creating a new SequentialPropertyNamer.  I'm unable as you said to get the CreateNew to fail, maybe I was completely mistaken (long hours, long days) when I thought the CreateNew was failing in a project using nbuilder.

I ended up implementing a test as I spoke about earlier, copying your parallel list test and just using a .CreateNew().Build() then checking all properties have an expected value of 1, which passes everytime without fail (as you mentioned, can't reproduce) so I could just be crazy!

However, I don't think it would hurt to also in CreateNew method instantiate a new instance of SequentialPropertyNamer like you did in the CreateListOfSize method, this would ensure no instance is reused between threads, right?

**Comment by oviradoi** [comment]
I have tried writing a test for CreateNew, similar to the one for CreateListOfSize. However, I could not get it to fail under any circumstances. It looks like you have tried the same thing and had the same result.

I also think that creating a new instance of SequentialPropertyNamer in CreateNew would not hurt, but I wanted to keep my pull request as simple as possible and I did not want to fix problems that I could not reproduce.

If the maintainers of nbuilder think this would be a good idea, I can update my pull request and also make that modification @PureKrome

**Comment by PureKrome** [comment]
I'm (was?) just a contributor but keeps an eye on this project :) @crmckenzie would have to make that final call.

**Comment by crmckenzie** [comment]
I could take a PR to make this better, but I think the problem is solvable by using a new `Builder` instance instead of using the static one. This is recommended anyway since the static `Builder` instance will be going away in a future version.

```csharp
public class Person
{
	public int Id { get; set; }
	public string Name { get; set; }
}

[TestFixture]
[Parallelizable(ParallelScope.All)]
public class TestClass
{
	private const int LIST_SIZE = 10;

	[Test]
	public void TestMethod([Range(0, 10)] int param)
	{
		IList<Person> persons = new Builder().CreateListOfSize<Person>(LIST_SIZE).Build();
		for (int i = 0; i < LIST_SIZE; i++)
		{
			Assert.AreEqual(i + 1, persons[i].Id);
			Assert.AreEqual("Name" + (i + 1), persons[i].Name);
		}
	}
}
```

**Comment by oviradoi** [comment]
@crmckenzie I have created a pull request over here: https://github.com/nbuilder/nbuilder/pull/92
If you think that creating a new instance of the builder is the way to go, then I can abandon the pull request.

**Comment by crmckenzie** [comment]
I appreciate that @oviradoi. Based on the code sample that is submitted in this issue, I think using an instance of `Builder` is the right choice. However, the same problem might still occur if the parallelized tests are using a common instance of `Builder`--so I think there's still room for the PR. 

I want to run the PR by a colleague who groks multi-threading better than I do before I accept it. This may take some time, but I think you can work around the problem you're experiencing for the time being. Let me know if I'm wrong.

**Comment by oviradoi** [comment]
@crmckenzie I can confirm that using a new instance of the Builder solves the problem. Switching all our tests to the new syntax is a pain, but is certainly doable. This is not a huge issue for us.

When reviewing the PR, please also investigate @mcockrellsana 's comments in order to see if applying the same patch in `CreateNew` makes sense.

Thanks for your help :)

**Comment by crmckenzie** [comment]
I think this issue is closed given the PR. Yes?

**Comment by oviradoi** [comment]
Yes, I would consider this fixed. Thanks :)
