### ISSUE TITLE
Obsoleting the static Builder? 

### ISSUE THREAD

**Issue by PureKrome** [nbuilder/nbuilder#95]
Hi @crmckenzie 👋 

I noticed in #91 that there is mention of obsoleting the `static Builder()`. Awesome ... (emphasis mine to highlight my question):

> I could take a PR to make this better, but I think the problem is solvable by using a new Builder instance instead of using the static one. This is recommended anyway **since the static Builder instance will be going away in a future version.**

Question: is there an ETA or plan on when this might happen. At least adding the `[obsolete]` attribute to give people a release cycle to prepare for the breaking change?

Cheers!

**Comment by crmckenzie** [comment]
Adding an `Obsolete` tag will happen sometime before 7.0. Once this is done I can start thinking about more advanced extensibility options for the builder configuration.

**Comment by PureKrome** [comment]
Awesome - thank you sir!
